image: Visual Studio 2017

branches:
  only:
  - master

clone_depth: 5

version: 0.1.{build}

platform:
  - x86
  - x64
  
configuration:
  - Release

build:
  project: SysmonX.sln
  verbosity: minimal
  parallel: true
